#!/usr/bin/env bash

echo ""
echo "======================================="
echo "Installing Software with Homebrew      "
echo "======================================="

# Homebrew
[ -z "$(which brew)" ] &&
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Taps (third-party repositories)
brew tap universal-ctags/universal-ctags
brew tap gwerbin/tap

# Languages
brew install python python3 ruby go

# Shells
brew install bash bash-completion
chsh -s /usr/local/bin/bash

# Terminal
brew install tmux tmux-xpanes reattach-to-user-namespace

# FZF
brew install fd ag ripgrep
brew install --HEAD https://raw.githubusercontent.com/junegunn/blsd/master/blsd.rb

# VIM
brew install cscope
brew install --HEAD universal-ctags

# Commandline software
brew install coreutils wget tree git stow dtrx hugo
brew install --HEAD neovim
brew install --HEAD gwerbin/tap/neovim-qt

# Apps
brew cask install iterm2 spotify firefox atom dropbox alfred \
     bartender 1password superduper fastscripts vlc amethyst \
     ansifilter fpp balenaetcher basictex \
     zotero transmit grammarly scrivener todour tunnelblick keyboard-maestro \
     xpra

echo ""
echo "======================================="
echo "Installing Software with pip           "
echo "======================================="

sudo pip3 install academic awscli pip_upgrade_outdated

echo ""
echo "======================================="
echo "Installing Software with tlmgr         "
echo "======================================="

sudo tlmgr install latexmk biblatex biber logreq \
  lastpage enumitem collection-fontsrecommended

echo ""
echo "======================================="
echo "Installing Software from Source        "
echo "======================================="

# Local bin
if [ ! -d "~/.local/bin" ]; then
  mkdir -p ~/.local/bin
fi

# Github
if [ ! -d "~/Cloud/Github" ]; then
  mkdir -p ~/Cloud/Github
fi

command -v blsd > /dev/null ||
  (bash <(curl -fL https://raw.githubusercontent.com/junegunn/blsd/master/install) && mv blsd ~/.local/bin)

if [ ! -e ~/.local/bin/z.sh ]; then
  curl https://raw.githubusercontent.com/rupa/z/master/z.sh -o ~/.local/bin/z.sh
fi

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
  curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

echo ""
echo "======================================="
echo "Configure OS specific software...      "
echo "======================================="

# remove icons from desktop
defaults write com.apple.finder CreateDesktop false
killall Finder

# disable inline attachment in mail
defaults write com.apple.mail DisableInlineAttachmentViewing -bool YES

# change screenshot location to ~/Pictures/Screenshots/
defaults write com.apple.screencapture location ~/Pictures/Screenshots/

# Change Script location to dotfiles
defaults write com.red-sweater.fastscripts ScriptTreePathsKey "("$dotfiles_dir/scpt")"

# fix hostname
if [ $? -eq 0 ] || echo $prompt | grep -q '^sudo:'; then
  sudo scutil --set HostName 'milano'
fi
