#!/usr/bin/env bash

old_stty_cfg=$(stty -g)

echo ""
echo "======================================="
echo "Do you want the usual with apt (y/n)   "
echo "======================================="
stty raw -echo ; ans_apt=$(head -c 1) ; stty $old_stty_cfg

echo ""
echo "======================================="
echo "Do you want the usual with pip (y/n)   "
echo "======================================="
stty raw -echo ; ans_pip=$(head -c 1) ; stty $old_stty_cfg

echo ""
echo "======================================="
echo "Do you want other usual (y/n)          "
echo "======================================="
stty raw -echo ; ans_source=$(head -c 1) ; stty $old_stty_cfg

# usual apt
if echo "$ans_apt" | grep -iq "^y" ;then
  sudo apt-get install software-properties-common

  sudo apt-get -y update
  sudo apt-get -y dist-upgrade

  sudo apt-get -y install build-essential \
      python-pip python3-pip \
      fd-find curl git stow tree neovim \
      tmux
fi

# usual pip
if echo "$ans_pip" | grep -iq "^y" ;then
  sudo pip3 install pip_upgrade_outdated
fi

# other usual
if echo "$ans_source" | grep -iq "^y" ;then
  command -v blsd > /dev/null ||
    (bash <(curl -fL https://raw.githubusercontent.com/junegunn/blsd/master/install) && mv blsd ~/.local/bin)

  if [ ! -e ~/.local/bin/z.sh ]; then
    curl https://raw.githubusercontent.com/rupa/z/master/z.sh -o ~/.local/bin/z.sh
  fi

  # git-prompt
  if [ ! -e ~/.git-prompt.sh ]; then
    curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
  fi

# tmux plugins
if echo "$ans_cfg_term" | grep -iq "^y" ;then
  # tmux
  if [ ! -d ~/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  fi
fi
