#!/usr/bin/env bash
#
# Yao Zheng (zheng.iao@icloud.com)
# 2011/05/25-

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
BASE=$(pwd)

if [ "$(uname -s)" = 'Darwin' ]; then
  # Homebrew
  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  # Taps (third-party repositories)
  brew tap waltarix/homebrew-customs
  brew tap universal-ctags/universal-ctags

  # Languages
  brew install python

  # Shells
  brew install bash bash-completion
  chsh -s /usr/local/bin/bash

  # Terminal
  brew install waltarix/homebrew-customs/tmux reattach-to-user-namespace

  # FZF
  brew install fd ag ripgrep
  brew install --HEAD https://raw.githubusercontent.com/junegunn/blsd/master/blsd.rb
  if [ ! -e ~/.local/bin/z.sh ]; then
    curl https://raw.githubusercontent.com/rupa/z/master/z.sh -o ~/.local/bin/z.sh
  fi

  # VIM
  brew install cscope
  brew install --HEAD universal-ctags

  # Commandline software
  brew install coreutils wget tree git stow dtrx hugo neovim

  # Apps
  brew cask install iterm2 spotify firefox atom dropbox alfred \
       bartender 1password superduper fastscripts vlc spectacle \
       zotero transmit oni flycut keycastr
fi

# bin
mkdir -p ~/.local/bin
stow --no-folding -d $BASE bin -t $HOME/.local/bin/

# cfg-core
stow --no-folding -d $BASE cfg-core -t $HOME/

# cfg-term
stow --no-folding -d $BASE cfg-term -t $HOME/

# scpt
defaults write com.red-sweater.fastscripts ScriptTreePathsKey '("$BASE/scpt")'

# remove icons from desktop
defaults write com.apple.finder CreateDesktop false
killall Finder

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
  curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

# nvim
ln -sf /usr/local/bin/nvim ~/.local/bin/vim

mkdir -p ~/.vim/autoload
curl -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

mkdir -p ~/.config/nvim/autoload
ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/

vim +PlugInstall +qall

# tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source-file ~/.tmux.conf

# fix hostname
sudo scutil --set HostName 'milano'
