#!/usr/bin/env bash
#
# Yao Zheng (zheng.iao@icloud.com)
# 2011/05/25-

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
BASE=$(pwd)

# Prime macos
if [ "$(uname -s)" = 'Darwin' ]; then
  # Homebrew
  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  # Taps (third-party repositories)
  brew tap universal-ctags/universal-ctags
  brew tap gwerbin/tap

  # Languages
  brew install python ruby go

  # Shells
  brew install bash bash-completion
  chsh -s /usr/local/bin/bash

  # Terminal
  brew install tmux tmux-xpanes reattach-to-user-namespace

  # FZF
  brew install fd ag ripgrep
  brew install --HEAD https://raw.githubusercontent.com/junegunn/blsd/master/blsd.rb

  # VIM
  brew install cscope
  brew install --HEAD universal-ctags

  # Commandline software
  brew install coreutils wget tree git stow dtrx hugo
  brew install --HEAD neovim
  brew install --HEAD gwerbin/tap/neovim-qt

  # Apps
  brew cask install iterm2 spotify firefox atom dropbox alfred \
       bartender 1password superduper fastscripts vlc amethyst \
       ansifilter fpp balenaetcher basictex \
       zotero transmit grammarly scrivener todour tunnelblick keyboard-maestro \
       xpra

  # remove icons from desktop
  defaults write com.apple.finder CreateDesktop false
  killall Finder
  
  # disable inline attachment in mail
  defaults write com.apple.mail DisableInlineAttachmentViewing -bool YES
  
  # change screenshot location to ~/Pictures/Screenshots/
  defaults write com.apple.screencapture location ~/Pictures/Screenshots/
  
  # Change Script location to dotfiles
  defaults write com.red-sweater.fastscripts ScriptTreePathsKey "("$BASE/scpt")"

  # fix hostname
  if [ $? -eq 0 ] || echo $prompt | grep -q '^sudo:'; then
    sudo scutil --set HostName 'milano'
  fi
fi

# Prime linux
if [ "$(uname -s)" = 'Linux' ]; then
  prompt=$(sudo -nv 2>&1)
  if [ $? -eq 0 ] || echo $prompt | grep -q '^sudo:'; then
    sudo add-apt-repository -y ppa:ubuntu-x-swat/updates
    sudo add-apt-repository -y ppa:greymd/tmux-xpanes
    sudo add-apt-repository -y ppa:longsleep/golang-backports

    sudo apt-get -y update
    sudo apt-get -y dist-upgrade

    sudo apt-get -y install build-essential golang-go curl git stow tree neovim \
      i3 py3status rofi conky \
      tmux tmux-xpanes \
      msmtp notmuch isync lbdb urlview \
      xdg-utils xpra mesa-utils \
      libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev autoconf libxcb-xrm0 libxcb-xrm-dev automake

    # clone the repository
    git clone https://www.github.com/Airblader/i3 $HOME/Cloud/Github/i3-gaps
    cd $HOME/Cloud/Github/i3-gaps

    # compile & install
    autoreconf --force --install
    rm -rf build/
    mkdir -p build && cd build/

    # Disabling sanitizers is important for release versions!
    # The prefix and sysconfdir are, obviously, dependent on the distribution.
    ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
    make
    sudo make install

    # Python
    # sudo pip3 install tzlocal
  fi

  # Kitty
  curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  ln -sf ~/.local/kitty.app/bin/kitty ~/.local/bin/

  # Dropbox
  [ -d ~/.dropbox-dist ] || (cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -)

  command -v dropbox > /dev/null ||
    (curl -fLo ~/.local/bin/dropbox https://www.dropbox.com/download?dl=packages/dropbox.py; chmod +x ~/.local/bin/dropbox)

  [ -f ~/.ssh/id_rsa ] || ssh-keygen
  # gnu-radio
  # sudo apt-get install python3-pip python-pip python-mako python-lxml
  # sudo pip3 install PyBOMBs
  
  # for server: su to root and do the following
  # pybombs auto-config
  # pybombs recipes add-defaults
  # pybombs prefix init /usr/local/ -a system_prefix -R gnuradio-default
fi

# bin
if [ ! -d "~/.local/bin" ]; then
  mkdir -p ~/.local/bin
fi
stow --no-folding -d $BASE bin -t $HOME/.local/bin/

command -v blsd > /dev/null ||
  (bash <(curl -fL https://raw.githubusercontent.com/junegunn/blsd/master/install) && mv blsd ~/.local/bin)

if [ ! -e ~/.local/bin/z.sh ]; then
  curl https://raw.githubusercontent.com/rupa/z/master/z.sh -o ~/.local/bin/z.sh
fi

# cfg-core
stow --no-folding -d $BASE cfg-core -t $HOME/

# cfg-term
stow --no-folding -d $BASE cfg-term -t $HOME/

# cfg-mail
mkdir -p ~/.mail/{personal, work}
stow --no-folding -d $BASE cfg-mail -t $HOME/
keyring set mbsync zheng.iao@icloud.com 

# tmux
if [ ! -d ~/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

tmux source-file ~/.tmux.conf
~/.tmux/plugins/tpm/bin/install_plugins

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
  curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

if [ ! -d ~/.vim/autoload ]; then
  mkdir -p ~/.vim/autoload
fi
curl -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

if [ ! -d ~/.config/nvim/autoload ]; then
  mkdir -p ~/.config/nvim/autoload
fi
ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/

nvim +PlugInstall +qall
