#!/usr/bin/env bash
#
# Yao Zheng (zheng.iao@icloud.com)
# 2011/05/25-

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
BASE=$(pwd)

if [ "$(uname -s)" = 'Darwin' ]; then
  # Homebrew
  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  # Taps (third-party repositories)
  brew tap waltarix/homebrew-customs
  brew tap universal-ctags/universal-ctags
  brew tap domt4/autoupdate

  # Automatic update/upgrade/cleanup homebrew
 brew autoupdate --start --upgrade --cleanup --enable-notification 

  # Languages
  brew install ruby python go

  # Shells
  brew install zsh fish bash-completion

  # Terminal
  brew install waltarix/homebrew-customs/tmux reattach-to-user-namespace

  # Email
  brew install neomutt/homebrew-neomutt/neomutt \
                 --with-sidebar-patch --with-notmuch-patch --HEAD \
               isync msmtp notmuch lbdb terminal-notifier lmdb

  # FZF
  brew install fd ag ripgrep jq highlight
  brew install --HEAD https://raw.githubusercontent.com/junegunn/blsd/master/blsd.rb
  if [ ! -e ~/.local/bin/z.sh ]; then
    curl https://raw.githubusercontent.com/rupa/z/master/z.sh -o ~/.local/bin/z.sh
  fi

  # VIM
  brew install cscope
  brew install --HEAD universal-ctags
  gem install gem-ctags
  gem ctags

  # Libraries
  brew install liboauth

  # Commandline software
  brew install coreutils wget tree git stow dtrx \
       ant leigingen sbt maven hugo \
       exiftool doxygen graphviz imagemagick gnuplot --with-qt@5.7 \
       ranger cmus

  # Apps
  brew cask install iterm2 spotify firefox atom dropbox alfred bartender 1password fastscripts spectacle flycut keycastr
fi

# bin
mkdir -p ~/.local/bin
stow --no-folding -d $BASE bin -t $HOME/.local/bin/

# cfg-core
stow --no-folding -d $BASE cfg-core -t $HOME/

# scpt
defaults write com.red-sweater.FastScripts ScriptTreePathsKey '("$BASE/scpt")'

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
  curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

# nvim
mkdir -p ~/Applications/Neovim/
curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz | tar xzf -C ~/Applications/Neovim/
ln -sf ~/Applications/Neovim/nvim-osx64/bin/nvim ~/.local/bin/vim

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

mkdir -p ~/.config/nvim/autoload
ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/

vim +PlugInstall +qall

# tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source-file ~/.tmux.conf
