#!/usr/bin/env bash

action=$1
shift

function usage(){
  echo "  Navigate to URL:"
  echo "    nav ITEM#"
  echo "      Searches for a URL in the todo line and launches an application."
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

if [[ $1 == "" ]]; then
  # TODO: solve color hardcoding problem
  id="$(nl -w3 -ba -s": " ${TODO_DIR}/todo.txt | grep -v "[0-9]\+\W\+x " | FZF_DEFAULT_OPTS='--no-bold --color=fg:7,fg+:3,bg:-1,bg+:-1,hl:5,hl+:5,prompt:8,pointer:3,marker:2' fzf | cut -f 1 -d ":")"
else
  id="$1"
fi

if [[ $id != "" ]]; then
  url=`sed -n "${id}s#.*](\(.*://[^)]\{0,\}\)).*#\1#p" "${TODO_DIR}/todo.txt"`
  if [[ $url = *"message"* ]]; then
    osascript -e 'tell app "Mail" to activate' -e 'tell app "Mail" to open location "'"${url}"'"'
  elif [[ $url = *"zotero"* ]]; then
    osascript -e 'tell app "Zotero" to activate' -e 'tell app "Zotero" to open location "'"${url}"'"'
  elif [[ $url = *"file"* ]]; then
    osascript -e 'tell app "Finder" to activate' -e 'tell app "Finder" to open location "'"${url}"'"'
  else
    sed -n ${id}p "${TODO_DIR}/todo.txt"
  fi
else
  2>&1 echo "invalid id"
  exit 1
fi

exit 0
